apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-react-app
  namespace: development
  labels:
    app: frontend-react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-react-app
  template:
    metadata:
      labels:
        app: frontend-react-app
    spec:
      containers:
      - name: frontend-react-app
        image: umairnaushad/frontend-react-app
        resources: 
          requests:
            cpu: "200m"
            memory: "200Mi"
          limits:
            cpu: "10000m"
            memory: "1000Mi"
      tolerations:
        - key: node-role
          operator: Equal
          value: development
          effect: NoSchedule

---
kind: Service
apiVersion: v1
metadata:
  name: frontend-react-app
  namespace: development
spec:
  selector:
    app: frontend-react-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 32100